apiVersion: v1
kind: Namespace
metadata:
  name: pkhub
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pkhub-secrets
  namespace: pkhub
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: pkhub
  name: pkhub-secrets-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["create", "update", "patch", "delete", "get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pkhub-secrets-role-binding
  namespace: pkhub
subjects:
- kind: ServiceAccount
  name: pkhub-secrets
  namespace: pkhub
roleRef:
  kind: ClusterRole
  name: pkhub-secrets-role
  apiGroup: rbac.authorization.k8s.io
